apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Release.Name }}-neo4j
  labels:
    app: {{ .Release.Name }}-neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-neo4j
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-neo4j
    spec:
      securityContext:
        runAsUser: 5533
        runAsGroup: 1279
        fsGroup: 5533
      volumes:
        - name: {{ .Release.Name }}-neo4j-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-neo4j-pvc
      containers:
        - name: neo4j
          image: ghcr.io/ebispot/ols4-neo4j:4.4.9-community
          volumeMounts:
            - mountPath: "/data"
              name: {{ .Release.Name }}-neo4j-storage
          resources:
            requests:
              memory: 4Gi
              cpu: 1
            limits:
              memory: 4Gi
              cpu: 1
          env:
            - name: NEO4J_HEAP_MEMORY
              value: 3g
            - name: NEO4J_dbms_memory_heap_maxSize
              value: 3g
            - name: NEO4J_AUTH
              value: none
          ports:
            - containerPort: 7474
            - containerPort: 7687
